# MATH&ML-1 Линейная алгебра в констекте линейных методов. Часть1
###  Содержание <a class="anchor" id=0></a>
- [1. Введение](#1)
- [2. Основные понятия линал. Векторы и действия над ними](#2)
- [2.1 Сложение векторов](#2-1)
- [2.2 Умножение векторов на скаляр](#2-2)
- [2.3 Скалярное произведение векторов](#2-3)
- [2.4 Свойства скалярного произведения векторов](#2-4)
- [2.5 Векторная запись модели линейной регрессии](#2-5)
- [3. Векторы. Практика](#3)
- [4. Основные понятия линал. Матрицы и действия над ними](#4)
- [5. Матрицы. Практика](#5)
- [6. Матричное умножение](#6)
- [7. Матричное умножение. Практика](#7)
- [8. Обратная матрица. Определитель матрицы](#8)
- [9. СЛАУ. Линейная зависимость векторов. Ранг матрицы. Базис](#9)
- [10. Обратная матрица, определитель, ранг. Практика](#10)
- [11. Итоги](#11)

# 1. Введение <a class="anchor" id=1></a>

[к содержанию](#0)

>**Линейная алгебра** — это раздел алгебры, который изучает объекты линейной природы, векторы и векторные пространства, матрицы и линейные операторы, которые они порождают, и системы линейных уравнений.

Линейная алгебра лежит в основе решения всех основных задач Data Science: создания и настройки моделей, создания и обучения нейросетей, корреляционного анализа и т. д. В конце концов, даже табличный способ представления данных — это тоже фундаментальная основа линейной алгебры, матрица.

**ЛИНЕЙНЫЕ МОДЕЛИ**

Все линейные модели, такие как линейная и логистическая регрессия, берут своё начало из линейной алгебры. Сюда же относят метод опорных векторов (`SVM`).

**МЕТОДЫ ПОНИЖЕНИЯ РАЗМЕРНОСТИ**

В основе метода главных компонент (`PCA`), который мы неоднократно использовали для понижения размерности пространства признаков, лежит теория векторных пространств. Сингулярное разложение (`SVD`), о котором мы поговорим в модуле по рекомендательным системам, — это способ разложения матрицы на компоненты.

**КОРРЕЛЯЦИОННАЯ МАТРИЦА**

Напомним, что корреляция — это мера линейной зависимости между признаками. Если признаков несколько, то корреляция превращается в знакомую нам корреляционную матрицу. Матрицы и операции с ними изучает именно линейная алгебра.

**ОБРАБОТКА ИЗОБРАЖЕНИЙ**

Известно, что современные компьютеры работают только с числами 0 и 1. Тогда как в компьютере можно сохранить изображение, состоящее из различных цветов? Легко! Для этого изображение представляется в виде матрицы, отражающей интенсивность пикселей. Затем эта матрица может быть обработана для определения цветов, предметов и т. д.

Любая операция, которую вы хотите выполнить с этим изображением, вероятно, будет «под капотом» использовать линейную алгебру и матрицы.

## ОСНОВЫ МАТЕМАТИЧЕСКОГО ЯЗЫКА: КВАНТОРЫ. ЧАСТЬ I

Прежде чем переходить к основной части материала, стоит вспомнить, что у математики есть свой «язык». Если вы читали статьи по математике, аналитике или машинному обучению, то могли заметить, что методы и функциональные зависимости там описываются на языке формул, который очень важно уметь понимать.

Возможно, со многими обозначениями вы уже знакомы, но стоит освежить их в памяти, чтобы дальше можно было без проблем понимать написанные формулировки. Разумеется, мы будем разбирать каждую тему на простых примерах, однако рядом всегда будем приводить и формальные обозначения. Для развития в Data Science (да и в любой науке, связанной с информатикой и математикой) большим бонусом является умение понимать математический язык, так как это даёт возможность читать различные статьи и понимать математические алгоритмы без дополнительных разъяснений.

Для начала познакомимся с **кванторами** и символами, позволяющими записывать математические формулировки:

* Символ $\forall$ читается как «для любого» и называется **квантором всеобщности**. Он заменяет собой слова «любой», «всякий», «для любого» и т. п.

* Символ $\exist$ читается как «существует» и называется **квантором существования**, а $\exist!$ читается как «существует единственный» и называется **квантором существования и единственности**. $\exist$ заменяет слова «существует», «найдётся» и т. п. 

* Знак импликации $\Rightarrow$ (или $\rightarrow$) воспринимается как замена слов «следует», «влечёт», «вытекает», «имеет место», «выполняется».

* Знак равносильности или эквивалентности $\leftrightarrow$ (или $\Leftrightarrow$) заменяет словосочетания «тогда и только тогда, когда», «в том и только том случае, когда», «если и только если».

* Двоеточие $:$ в математических формулах читается как «такой, что».

* Вертикальная черта $|$ означает «при условии, что».

# 2. Основные понятия линал. Векторы и действия над ними <a class="anchor" id=2></a>

[к содержанию](#0)

На уроках геометрии в школе вам рассказывали, что вектор — это отрезок, соединяющий две точки в пространстве и имеющий направление. Например, вектор $\overrightarrow{AB}$, представленный на рисунке ниже, соединяет две точки, $А$ и $B$. Направление вектора указывается от точки $А$ к точке $B$.

>В строгом математическом смысле под вектором понимается часть некоторого векторного пространства с множеством различных свойств, но об этом мы поговорим чуть позже.

В `Python` тоже есть своё понятие вектора, например это одномерный numpy-массив или список из чисел.

Давайте введём наиболее общее определение, которое подойдёт ко всем случаям.

>**Вектор** — это набор чисел, записанных в определённом порядке (в столбец или в строку).

Вектор, состоящий из $m$ координат, записывается следующим образом: $\overrightarrow{s}=(s_1, s_2, ..., s_m)$
или $\overrightarrow{s}=\left( \begin{array}{c} s_1 \\ s_2 \\ \dots \\ s_m \end{array} \right)$

>Примечание. Стрелка наверху $\overrightarrow{s}$ указывает на то, что переменная $s$ является вектором. Однако нередко в литературе для краткости записи стрелку опускают и записывают просто $s=(s_1, s_2, ..., s_m)$. Мы будем придерживаться математического формализма и ставить стрелку для обозначения вектора.

Давайте сразу рассмотрим пример из жизни.

Агентство недвижимости «Рай в шалаше» занимается сдачей жилья в аренду. Данные по объектам в одном районе Москвы за последний месяц представлены в таблице ниже.

Столбцы этой таблицы мы можем рассмотреть в качестве векторов, получив информацию о каждой квартире по одному параметру, например по величине арендной платы (вектор $\overrightarrow{s}$). Если взять в качестве векторов строки таблицы, то мы увидим срез всех параметров по одной квартире (вектор $\overrightarrow{f}$).

<img src=m1_img1.png width=800>

>
>Числа $s_1, s_2, ..., s_m$ называются **координатами вектора**, а количество этих координат ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=m$ называется размерностью вектора.

**Примечание**. Векторы $\overrightarrow{s}$ и $\overrightarrow{f}$ из прошлого примера имели размерности $dim(\overrightarrow{s}){=4,\ \ dim \left(\overrightarrow{f}\right)\ }=5$.

Агентство недвижимости выставило за неделю несколько квартир площадью 33, 65, 50 и 45 кв. м. Сколько всего квартир выставлено за неделю? Какова площадь квартиры № 3?

Решим нашу задачу с помощью векторного инструментария. Составим вектор $\overrightarrow{s}=(33, 65, 50, 45)$ из площадей квартир.

Количество квартир равно размерности вектора $\overrightarrow{s}$. Размерность — количество координат: ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=4$

Площадь третьей квартиры — это третья координата вектора: $s_3 = 50м^2$

Теперь рассмотрим, что представляет собой вектор в `Python`.

In [6]:
import numpy as np

s = np.array([33, 65, 50, 45])
print('Всего квартир:',len(s)) 
print('Площадь 3-й квартиры:', s[2],'м2' ) 

Всего квартир: 4
Площадь 3-й квартиры: 50 м2


In [11]:
#Дан вектор в Python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), 
# содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно. 
# Будем считать, что температура в январе — t_0, то есть отсчёт индексов идёт с нуля.

t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
np.mean(t)

21.25

## ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ ВЕКТОРА. ВЕКТОРНОЕ ПРОСТРАНСТВО

Рядом с линейной алгеброй всегда идёт наука под названием **аналитическая геометрия**. Поэтому, говоря о векторах, нельзя не упомянуть о его геометрической интерпретации, чтобы создать целостное понимание. Геометрический смысл вектора поможет понять, что такое **векторное пространство**.

>**Примечание**. Приведённая геометрическая интерпретация справедлива как для векторов, записанных в строку, так и для векторов, записанных в столбец.

Пусть у нас есть какой-то вектор $\overrightarrow{s}=\left(s_1, s_2\right)$ размерности ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=2$.

Выберем прямоугольную систему координат $S_1OS_2$, на которой будем откладывать две точки на плоскости $P_1=(x_1,y_1)$ и ,$P_2=(x_2,y_2)$ такие, чтобы выполнялось условие:

$s_1=x_2-x_1$ и $s_2=y_2-y_1$

Проведём из точки $P_1$ в точку $P_2$ направленный отрезок $\overrightarrow{P_1 P_2}$:

<img src=m1_img2.png>


Координатами отрезка $\overrightarrow{P_1P_2}$ будет разница между соответствующими координатами конца и начала отрезка, а это и будет вектор $\overrightarrow{s}$: 
$$\overrightarrow{s}=\overrightarrow{P_1P_2}=\left(x_2-x_1,\ y_2-y_1\right)=(s_1,\ s_2)$$

>Таким образом, любой вектор $\overrightarrow{s}$ размерности 2 можно интерпретировать как направленный отрезок, имеющий конец и начало.

Любой отрезок, даже направленный, имеет длину. Длина вектора $\overrightarrow{s}$ обозначается как $|s|$ и определяется как гипотенуза треугольника ${\Delta }_{P_0P_1P_2}$ по теореме Пифагора:

$$\left|\overrightarrow{s}\right|=\sqrt{{\left(x_2-x_1\right)}^2+{\left(y_2-y_1\right)}^2}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2}$$

Давайте посмотрим конкретный пример с конкретными числами. 

Пусть есть вектор $\overrightarrow{s}=(4,3)$. Построим две точки $P_1=(4, 1)$ и $P_2=(8, 4)$ в системе координат $S_1 O S_2$ и соединим их направленным отрезком с направлением от точки $P_1$ к точке $P_2$. Тогда этот направленный отрезок и есть вектор $\overrightarrow{s}$

Длина вектора  будет равна: $\left|\overrightarrow{s}\right|=\sqrt{{\left(8-4\right)}^2+{\left(4-1\right)}^2}=\sqrt{{\left(4\right)}^2+{\left(3\right)}^2}=\sqrt{2}5=5$

<img src=m1_img3.png width=400>

Почему мы выбираем именно точки $P_1=(4,1)$ и $P_2=(8,4)$? Ведь можно построить вектор  и другими способами, например:
$$P_1=\left(2,\ 2\right),\ P_2=\left(6,\ 5\right):\ \ \overrightarrow{P_1P_2}=\left(6-2,\ 5-2\right)=(4,\ 3)$$
$$P_1=\left(2,\ -3\right),\ P_2=\left(6,\ 0\right):\ \ \overrightarrow{P_1P_2}=\left(6-2,\ 0-(-3)\right)=(4,\ 3)$$
$$P_1=\left(0,\ 0\right),\ P_2=\left(4,\ 3\right):\ \ \overrightarrow{P_1P_2}=\left(4-0,\ 3-0\right)=(4,\ 3)$$

Верно. Все предложенные комбинации точек $P_1$ и $P_2$ задают вектор $\overrightarrow{s}$.

<img src=m1_img4.png width=400>

Сколько комбинаций точек $P_1$ и $P_2$ можно придумать? Если подумать, бесконечное множество. Получается, существует бесконечное количество векторов $\overrightarrow{s}$? 

**И да, и нет.** Если посмотреть на приведённый выше рисунок, можно заметить, что все векторы имеют одинаковую длину  $|\overrightarrow{s}|=5$, а также параллельны друг другу и имеют одно и то же направление. В этом случае говорят, что векторы **сонаправлены и равны друг другу**. Тогда все векторы можно совместить в один с помощью параллельного переноса в какую-то точку на плоскости. 

В линейной алгебре в качестве такой точки принята точка начала системы координат $O=(0,0)$. Таким образом, начало всех возможных векторов $\overrightarrow{s}$ переносится в точку $O$ и геометрическая интерпретация вектора $\overrightarrow{s}$ размерности 2 обретёт новый смысл.

>Вектор $\overrightarrow{\boldsymbol{s}}\boldsymbol{=(}{\boldsymbol{s}}_{\boldsymbol{1}}\boldsymbol{,\ }{\boldsymbol{s}}_{\boldsymbol{2}}\boldsymbol{)}$ задаёт в прямоугольной системе координат $S_1 O S_2$ отрезок, направленный из начала системы $O=(0,0)$ координат в точку с координатами $P=(s_1,s_2)$

Сколько всего различных между собой векторов можно построить в системе координат $S_1 O S_2$? Опять же — бесконечное множество! Мы можем провести сколько угодно векторов с началом в точке $(0,0)$. На рисунке ниже представлено шесть таких векторов: 

<img src=m1_img5.png width=400>

Множество всех возможных векторов $S$ называют **векторным пространством**. Говорят: вектор $\overrightarrow{s}=(s_1, s_2)$ принадлежит векторному пространству $S$. Запись: $$\overrightarrow{s}\in S$$

В свою очередь, каждая координата векторов $s_1$ и $s_2$ является действительным числом, то есть принадлежит множеству действительных чисел. В математике оно обозначается за $\mathbb{R}$. Запись: $$s_1\in \mathbb{R}, s_2\in \mathbb{R}$$

Так как размерность вектора равна 2, то векторное пространство $S$ является частью двухмерного пространства действительных чисел и обозначается как $\mathbb{R^2}$. Запись: $$S\subset {\mathbb{R}}^2$$

Отсюда: $\overrightarrow{s}\in S\subset {\mathbb{R}}^2$. Для краткости часто пишут: $$\overrightarrow{s}\in \mathbb{R}^2$$

Последняя запись «переводится» как «Задан вектор $\overrightarrow{s}$ размерности ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=2$, такой, что его координаты являются действительными числами».

В общем случае вектор $\overrightarrow{\boldsymbol{s}}\boldsymbol{=(}{\boldsymbol{s}}_{\boldsymbol{1}}\boldsymbol{,\ }{\boldsymbol{s}}_{\boldsymbol{2}}\boldsymbol{,\ \dots ,\ }{\boldsymbol{s}}_{\boldsymbol{m}}\boldsymbol{)}$ размерностью ${\mathrm{dim} \left(\overrightarrow{s}\right)\ }=m$ задаёт в векторном $m$-мерном пространстве $\boldsymbol{S}\boldsymbol{\subset }{\mathbb{R}}^{\boldsymbol{m}}$ направленный отрезок с началом в точке $O=(0,0,...,0)$ и концом в точке $(s_1,s_2,...,s_m)$. 

>**Примечание**. Для краткости точку $О$ можно записать в виде вектора со всеми координатами, равными $0$. Такой вектор называется **нулевым вектором** и обозначается как $\overrightarrow{0}=(0, 0,\ \dots, 0)$.
>
>Длина такого вектора  будет вычисляться так: $$\overrightarrow{s}=\sqrt{{\left(s_1\right)}^2+{\left(s_2\right)}^2+\dots +{\left(s_m\right)}^2}=\sqrt{\sum^m_{j=1}{{\left(s_j\right)}^2}}$$

Вернёмся к примеру с арендой квартир. Пусть у нас есть четыре квартиры, которые характеризуются тремя признаками (арендная плата, площадь, число показов в день), представленными в таблице (привычный нам DataFrame):

| **№ квартиры** | **Арендная плата (тыс. руб.)** | **Площадь (кв. м)** | **Количество комнат** | **Этаж** | **Показов в день** |
| - | - | - | - | - | - |
| 1 | 65 | 50 | 3 | 5 | 8 |
| 2 | 70 | 52 | 2 | 12 | 4 |
| 3 | 120 | 80 | 1 | 10 | 5 |
| 4 | 35 | 33 | 1 | 3 | 10 |

Тогда каждую квартиру можно обозначить за вектор-строку $\overrightarrow{s_j}$.

Если мы возьмём значения признаков, описывающих каждую квартиру, в качестве векторов , то получим четыре вектора следующего вида: ${\overrightarrow{s}}_1,\ {\overrightarrow{s}}_2, \dots , {\overrightarrow{s}}_4$

$${\overrightarrow{s}}_1=\left(s_{11},\ s_{12},\ s_{13},\ s_{14},s_{15}\right)=(65,\ 60,\ 3,\ 6,\ 8)$$
$${\overrightarrow{s}}_2=\left(s_{21},\ s_{22},\ s_{23},\ s_{24},s_{25}\right)=(70,\ 52,\ 2,\ 12,\ 4)$$
$${\overrightarrow{s}}_3=\left(s_{31},\ s_{32},\ s_{33},\ s_{34},s_{35}\right)=(120,\ 80,\ 1,\ 10,\ 5)$$
$${\overrightarrow{s}}_4=\left(s_{41},\ s_{42},\ s_{43},\ s_{44},s_{45}\right)=(35,\ 33,\ 1,\ 3,\ 10)$$

>**Примечание**. Здесь первый индекс координаты обозначает номер вектора, а второй индекс — номер его координаты.

Таким образом, у нас есть четыре вектора $\overrightarrow{s_j}$., которые принадлежат некоторому векторному пространству с размерностью $dim=5: S\subset {\mathbb{R}}^5$.

В общем случае квартир может быть больше, в пределе — бесконечное множество. Тогда векторное пространство  описывает множество всевозможных квартир, характеризующихся координатами-признаками, которые приведены в таблице.

## БАЗОВЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

Внутри любого векторного пространства должны быть определены следующие операции с векторами:

* Сложение/вычитание векторов. Результат — **вектор**.
* Умножение вектора на скаляр (число). Результат — **вектор**.
* Линейная комбинация векторов. Результат — **вектор**.

## СЛОЖЕНИЕ/ВЫЧИТАНИЕ ВЕКТОРОВ <a class="anchor" id=2-1></a>

[к содержанию](#0)

Сложение векторов происходит поэлементно: первая координата складывается с первой, вторая — со второй и так далее.

Давайте скажем то же самое на языке линейной алгебры ↓

Пусть заданы два вектора ${\overrightarrow{v}}_1$ и $\overrightarrow{v}_2$ из одного векторного пространства $V\subset {\mathbb{R}}^m$: 

 $\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)$ и $\overrightarrow{v_2}=\left( \begin{array}{c} v_{21} \\ v_{22} \\ \dots \\ v_{2m} \end{array} \right)$

Тогда сумма двух векторов ${\overrightarrow{v}}_1$ и $\overrightarrow{v}_2$ определяется как новый вектор $\overrightarrow{v}_3$, принадлежащий тому же векторному пространству $V$, с координатами: 

$\overrightarrow{v_3}=\overrightarrow{v_1}+\overrightarrow{v_2}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)+\left( \begin{array}{c} v_{21} \\ v_{22} \\ \dots \\ v_{2m} \end{array} \right)=\left( \begin{array}{c} v_{11}+v_{21} \\ v_{12}+v_{22} \\ \dots \\ v_{1m}+v_{2m} \end{array} \right)$

Формально разницы между векторами в линейной алгебре не определяется. Разница — это комбинация двух операций: сложение и умножение на число. Но для начального понимания нам достаточно знать, что вычитаются векторы также поэлементно.

$\overrightarrow{v_3}=\overrightarrow{v_2}-\overrightarrow{v_1}=\overrightarrow{v_2}+\left(-1\right)\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)-\left( \begin{array}{c} v_{21} \\ v_{22} \\ \dots \\ v_{2m} \end{array} \right)=\left( \begin{array}{c} v_{11}-v_{21} \\ v_{12}-v_{22} \\ \dots \\ v_{1m}-v_{2m} \end{array} \right)$

In [1]:
import numpy as np

a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
a + b
## array([15, 23, 14,  8])
a - b
## array([ 5, -7, -4, -6])

array([ 5, -7, -4, -6])

## УМНОЖЕНИЕ ВЕКТОРА НА СКАЛЯР <a class="anchor" id=2-2></a>

[к содержанию](#0)

Умножение вектора на число также происходит поэлементно, то есть каждая координата вектора умножается на заданное число.

Включаем «переводчик» на язык линейной алгебры. 

Пусть задан вектор $\overrightarrow{v_1}$ из векторного пространства $V\subset {\mathbb{R}}^m$:

$\overrightarrow{v_1}=\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)$

Тогда результатом умножения векторов $\overrightarrow{v_1}$ на число $w\in{\mathbb{R}}$ называется **новый вектор** $\overrightarrow{v_2}$, принадлежащий тому же векторному пространству $V$, с координатами:

$\overrightarrow{v_2}=\omega \overrightarrow{v_1}=\omega \left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)=\left( \begin{array}{c} \omega v_{11} \\ \omega v_{12} \\ \dots \\ \omega v_{1m} \end{array} \right)$

>Векторы $\overrightarrow{v_1}$ и $\overrightarrow{v_2}$ пропорциональны друг другу с коэффициентом $w$. По-другому такие векторы называются **коллинеарными**. Обозначается: $\overrightarrow{v_1} || \overrightarrow{v_2}$.

Если коэффициент пропорциональности положительный ($w>0$), векторы **сонаправлены** (смотрят в одном направлении), если отрицательный ($w<0$) — **противоположно** направлены. Геометрически это значит, что векторы лежат на одной прямой (**или параллельных прямых**) и направлены в одну или противоположные стороны. О геометрической интерпретации мы поговорим чуть позже.

In [2]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

>Примечание. Отметим особые случаи сложения векторов и умножения на скаляр:
>
>
>* Сложение противоположно направленных векторов всегда даёт нулевой вектор:
>
>$\overrightarrow{v_1}=\left( \begin{array}{c} 10 \\ 8 \end{array} \right)$ и $\overrightarrow{v_2}=\left( \begin{array}{c} -10 \\ -8 \end{array} \right)$
>
>$\overrightarrow{v_3}=\overrightarrow{v_1}+\overrightarrow{v_2}=\left( \begin{array}{c} 10-10 \\ 8-8 \end{array} \right)=\left( \begin{array}{c} 0 \\ 0 \end{array} \right)=\overrightarrow{0}$
>
>* Умножение вектора на $w=0$ также всегда даёт нулевой вектор:
>
>$\overrightarrow{v_1}=\left( \begin{array}{c} 10 \\ 8 \end{array} \right)$ и $w=0$
>
>$\overrightarrow{v_2}=\omega \overrightarrow{v_1}=0\left( \begin{array}{c} 10 \\ 8 \end{array} \right)=\left( \begin{array}{c} 0 \\ 0 \end{array} \right)=\overrightarrow{0}$
>
>* Умножение любого скаляра $w=0$ на нулевой вектор $\overrightarrow{0}$ всегда даёт нулевой вектор:
>
>$\overrightarrow{0}=\left( \begin{array}{c} 0 \\ 0 \end{array} \right)$ и $w=14999$
>
>$\overrightarrow{v}=\omega \overrightarrow{0}=104320\left( \begin{array}{c} 0 \\ 0 \end{array} \right)=\left( \begin{array}{c} 0 \\ 0 \end{array} \right)=\overrightarrow{0}$
>
>.


In [9]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2,3,2.5])
a+b+c*72

array([394., 496., 500.])

## ГЕОМЕТРИЧЕСКАЯ ИНТЕРПРЕТАЦИЯ БАЗОВЫХ ОПЕРАЦИЙ С ВЕКТОРАМИ

Давайте рассмотрим операции сложения и умножения на скаляр с точки зрения геометрии. Рассмотрим двухмерный случай. Пусть есть два вектора:

$\overrightarrow{v_3}=\overrightarrow{v_1}+\overrightarrow{v_2}=\left( \begin{array}{c} 8 \\ 5 \end{array} \right)+\left( \begin{array}{c} 3 \\ -2 \end{array} \right)=\left( \begin{array}{c} 11 \\ 3 \end{array} \right)$

Построим все векторы на плоскости $V_1OV_2$.

Видно, что если в конец вектора $\overrightarrow{v_1}$ дорисовать вектор, параллельный $\overrightarrow{v_2}$ и совпадающий с ним по длине, а в конец вектора $\overrightarrow{v_2}$ дорисовать вектор, параллельный $\overrightarrow{v_1}$ и совпадающий с ним по длине, то мы получим параллелограмм, построенный на векторах $\overrightarrow{v_1}$ и $\overrightarrow{v_2}$. Вектор-сумма $\overrightarrow{v_3}$ будет в точности равен диагонали этого параллелограмма.

<img src=m1_img6.png width=400>

In [11]:
a = np.array([4,6])
b = np.array([-1,-2])
# длина вектора
np.linalg.norm(a+b)

5.0

## ЛИНЕЙНАЯ КОМБИНАЦИЯ ВЕКТОРОВ

**Линейная комбинация** — это объединение операций сложения векторов и умножения на скаляр в одну. Каждый вектор умножается на соответствующий ему коэффициент, все умноженные векторы складываются.

**Линейной комбинацией** из $n$ векторов $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_n}$, каждый из которых принадлежит векторному пространству $\overrightarrow{v_i}\in V\subset {\mathbb{R}}^m$, называется новый вектор $u\in{V}$, такой, что:

$u={\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_n\overrightarrow{v_n}={\omega }_1\left( \begin{array}{c} v_{11} \\ v_{12} \\ \dots \\ v_{1m} \end{array} \right)+{\omega }_2\left( \begin{array}{c} v_{21} \\ v_{22} \\ \dots \\ v_{2m} \end{array} \right)+\dots +{\omega }_n\left( \begin{array}{c} v_{n1} \\ v_{n2} \\ \dots \\ v_{nm} \end{array} \right)$,

где ${\omega }_i\in \mathbb{R}$ — коэффициенты линейной комбинации.

## НУЛЕВАЯ ЛИНЕЙНАЯ КОМБИНАЦИЯ

Самое интересное в линейных комбинациях — это особые случаи, а именно **нулевая линейная комбинация**. 

Линейная комбинация векторов называется **нулевой**, если результат линейной комбинации равен нулевому вектору:

$\overrightarrow{u}={\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_n\overrightarrow{v_n}=\left( \begin{array}{c} 0 \\ 0 \\ \dots \\ 0 \end{array} \right)=\overrightarrow{0}$

Как получить нулевой вектор из линейной комбинации? Самый простой вариант — чтобы все коэффициенты линейной комбинации были равны $0$. Однако такой случай, называемый **тривиальным**, нам не интересен.

>Нулевая линейная комбинация называется **тривиальной**, если все коэффициенты $w_i$ равны $0$. 
>
>На формальном языке линейной алгебры это записывается так:
>
>$\overrightarrow{u}={\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_n\overrightarrow{v_n}=\overrightarrow{0}-\textrm{т}\textrm{р}\textrm{и}\textrm{в}\textrm{и}\textrm{а}\textrm{л}\textrm{ь}\textrm{н}\textrm{а}\textrm{я},\textrm{е}\textrm{с}\textrm{л}\textrm{и}\ \forall {\omega }_i=0,\ \ i=1,\ 2,\ \dots ,\ n,$
>
>Переводится так: «Вектор $\overrightarrow{u}$ равен нулевому вектору, когда все ($\forall$) коэффициенты $w_i$ равны $0$».

Нулевая линейная комбинация называется **нетривиальной**, если хотя бы один из коэффициентов отличен от $0$.

На формальном языке линейной алгебры это записывается так: 

$\overrightarrow{u}={\omega }_1\overrightarrow{v_1}+{\omega }_2\overrightarrow{v_2}+\dots +{\omega }_n\overrightarrow{v_n}=\overrightarrow{0}-\textrm{н}\textrm{е}\textrm{т}\textrm{р}\textrm{и}\textrm{в}\textrm{и}\textrm{а}\textrm{л}\textrm{ь}\textrm{н}\textrm{а}\textrm{я}\ ,\ \textrm{е}\textrm{с}\textrm{л}\textrm{и}\ \exists {\omega }_i\neq 0,\ \ i=1,\ 2,\ \dots ,\ n,$

Переводится так: «Существует ($\exist$) хотя бы один такой коэффициент, отличный от нуля ${\omega }_i\neq 0$, при котором вектор $\overrightarrow{u}$ равен нулевому вектору».

## ЛИНЕЙНАЯ (НЕ)ЗАВИСИМОСТЬ

Предположим, что нам удалось составить нетривиальную комбинацию, то есть удалось подобрать такие $w_i \neq{0}$, что вектор $\overrightarrow{u}=\overrightarrow{0}$.

>В таком случае векторы, из которых была составлена линейная комбинация $\overrightarrow{v_1},\ \overrightarrow{v_2},\ \dots ,\ \overrightarrow{v_n}$, называются **линейно зависимыми**.

Тогда хотя бы один из векторов, но не обязательно любой, в линейной комбинации можно выразить через другие векторы, представив его как линейную комбинацию.

>Или же, возможно, как мы ни старались, но нам не удалось подобрать такие коэффициенты $w_i \neq{0}$, чтобы составить нулевую нетривиальную линейную комбинацию. Такие векторы называются **линейно независимыми**. В таком случае ни один из векторов не выражается через другие векторы.

In [13]:
a = np.array([4,5])
b = np.array([2,1])
c = np.array([1,0])
x = np.array([-7,-7])
a*2 + b*-3 + c*5 + x

array([0, 0])

In [14]:
a = np.array([3,4,5,9])
b = np.array([1,5,3,6])
b*400 - a*200 

array([-200, 1200,  200,  600])

## СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ ВЕКТОРОВ <a class="anchor" id=2-3></a>

[к содержанию](#0)

Существует четыре способа умножить векторы между собой:

* Скалярное произведение. Результат — **число**. 
* Векторное произведение. Результат — **вектор**.
* Смешанное произведение. Результат — **число**. 
* Тензорное произведение. Результат — **матрица**.

>Чтобы найти **скалярное произведение двух векторов**, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится.

Пусть заданы два вектора $\overrightarrow{v}_1$ и $\overrightarrow{v}_2$ из одного векторного пространства $V\mathrm{\subset }{\mathbb{R}}^m$:

$\overrightarrow{v_{\mathrm{1}}}\mathrm{=}\left( \begin{array}{c} v_{\mathrm{11}} \\ v_{\mathrm{12}} \\ \mathrm{\dots } \\ v_{\mathrm{1}m} \end{array} \right)$ и $\overrightarrow{v_{\mathrm{2}}}\mathrm{=}\left( \begin{array}{c} v_{\mathrm{21}} \\ v_{\mathrm{22}} \\ \mathrm{\dots } \\ v_{\mathrm{2}m} \end{array} \right)$

Тогда скалярным произведением векторов $\overrightarrow{v}_1$ и $\overrightarrow{v}_2$ называется число, равное сумме произведений координат векторов. 

Скалярное произведение обозначается как $(\overrightarrow{v}_1,\overrightarrow{v}_2)$ или символом точки: $\overrightarrow{v_{\mathrm{1}}}\cdot \overrightarrow{v_{\mathrm{2}}}$.

$\left(\overrightarrow{v_{\mathrm{1}}},\ \overrightarrow{v_{\mathrm{2}}}\right)=\overrightarrow{v_{\mathrm{1}}}\cdot \overrightarrow{v_{\mathrm{2}}}=v_{\mathrm{11}}v_{\mathrm{21}}+v_{\mathrm{12}}v_{\mathrm{22}}+\dots v_{\mathrm{1}m}v_{\mathrm{2}m}=\sum^m_{i=1}{v_{1i}v_{2i}}$

В Numpy скалярное произведение вычисляется при помощи `np.dot()`

## ДЛИНА ВЕКТОРА ЧЕРЕЗ СКАЛЯРНОЕ ПРОИЗВЕДЕНИЕ

Через скалярное произведение можно выразить длину вектора (обозначается как $|\overrightarrow{v}|$).

Ранее мы говорили, что длина вектора определяется по теореме Пифагора как гипотенуза:

$\left|\overrightarrow{v}\right|=\sqrt{{\left(v_1\right)}^2+{\left(v_2\right)}^2+\dots +{\left(v_m\right)}^2}=\sqrt{\sum^m_{j=1}{{\left(v_j\right)}^2}}$

Но, если вспомнить школьную математику, можно заметить, что возведение в квадрат — ${\left(v_j\right)}^2=v_jv_j$. Тогда длина вектора вычисляется так:

$\left|\overrightarrow{v}\right|=\sqrt{v_1v_1+v_2v_2+\dots +v_mv_m}=\sqrt{\sum^m_{j=1}{v_jv_j}}$

Не кажется ли вам выражение под корнем очень знакомым? Это скалярное произведение вектора $\overrightarrow{v}$ с самим собой. Тогда длина вектора $\overrightarrow{v}$ равна:

$\left|\overrightarrow{v}\right|=\sqrt{\left(\overrightarrow{v},\ \overrightarrow{v}\right)}=\sqrt{\overrightarrow{v}\cdot\overrightarrow{v}}=\sqrt{v_1v_1+v_2v_2+\dots +v_mv_m}$

>Таким образом, в линейной алгебре **длина вектора** определяется как квадратный корень из скалярного произведения вектора с самим собой.

## СВОЙСТВА СКАЛЯРНОГО ПРОИЗВЕДЕНИЯ <a class="anchor" id=2-4></a>

[к содержанию](#0)

* **Линейность**

Всем знакомо правило раскрытия скобок при умножении чисел: $\left(a+b\right)\left(c+d\right)=ac+ad+bc+bd$

Скалярное произведение ведёт себя точно так же: $\left(\overrightarrow{a}+\overrightarrow{b},\ \overrightarrow{c}+\overrightarrow{d}\right)=\left(\overrightarrow{a},\ \overrightarrow{c}\right)+\left(\overrightarrow{a},\ \overrightarrow{d}\right)+\left(\overrightarrow{b},\ \overrightarrow{c}\right)+(\overrightarrow{b},\ \overrightarrow{d})$

* Скалярное произведение двух векторов $\overrightarrow{v}_1$ и $\overrightarrow{v}_2$ в точности равно произведению длин этих векторов $|\overrightarrow{v}_1|$ и $|\overrightarrow{v}_2$| на косинус угла между ними $\mathrm{cos}\mathrm{}(\overrightarrow{v_1},\ \overrightarrow{v_2})$:

$\left(\overrightarrow{v_1},\ \overrightarrow{v_2}\right)=\left|\overrightarrow{v_1}\mathrm{\ }\right|\ \left|\overrightarrow{v_2}\right|{\mathrm{cos} \left(\widehat{\overrightarrow{v_1},\ \overrightarrow{v_2}}\right)\ }$

Из этого свойства следует **замечательная формула** определения косинуса угла между векторами:

${\mathrm{cos} \left(\widehat{\overrightarrow{v_1},\ \overrightarrow{v_2}}\right)\ }=\frac{\left(\overrightarrow{v_1},\ \overrightarrow{v_2}\right)}{\left|\overrightarrow{v_1}\mathrm{\ }\right|\ \left|\overrightarrow{v_2}\right|}$ 

* Из последнего свойства следует ещё одно свойство скалярного произведения. Если скалярное произведение двух векторов $\overrightarrow{v}_1$ и $\overrightarrow{v}_2$ равно $0$, то **вектора ортогональны** (находятся под углом 90°). И наоборот: если вектора ортогональны друг другу, их скалярное произведение $(\overrightarrow{v_1},\ \overrightarrow{v_2})$ равно 0.

$\left(\overrightarrow{v_1},\ \overrightarrow{v_2}\right)=0\Leftrightarrow \overrightarrow{v_1}\bot \overrightarrow{v_2}$

<img src=m1_img7.png width=200>

Свойство **ортогональности векторов** применяется для определения линейной зависимости между ними, о которой поговорим чуть позже.

## Векторная запись модели линейной регрессии <a class="anchor" id=2-5></a>

[к содержанию](#0)

Ответ модели линейной регрессии $\hat{y}$ (выход) вычислялся как сумма параметров модели $w_1,w_2,\dots, w_m$ на соответствующие значения признаков $x_1,x_2,\dots,x_m$ плюс некоторый коэффициент смещения $w_0$:

$\hat{y}={\omega }_0+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$

Давайте добавим коэффициент 1 перед параметром $w_0$:

$\hat{y}={\omega }_01+{\omega }_1x_1+{\omega }_2x_2+\dots +{\omega }_mx_m$

А теперь представим параметры модели в виде вектора $\overrightarrow{w}$ и признаки — в виде вектора $\overrightarrow{x}$:

$\overrightarrow{\omega }=\left( \begin{array}{c} {\omega }_0 \\ {\omega }_1 \\ {\omega }_2 \\ \dots \\ {\omega }_m \end{array} \right)\ \textrm{и}\ \overrightarrow{x}=\left( \begin{array}{c} 1 \\ x_1 \\ x_2 \\ \dots \\ x_m \end{array} \right)$

Тогда уравнение линейной регрессии можно записать в лаконичной векторной форме скалярного произведения двух векторов $\overrightarrow{w}$ и $\overrightarrow{x}$:

$\hat{y}=\overrightarrow{w}\cdot \overrightarrow{x}$

# 3. Векторы. Практика <a class="anchor" id=3></a>

[к содержанию](#0)

Задача (условие № 1)

Агентство «Рай в Шалаше» недавно сдало в аренду четыре квартиры в одном доме.

* Общая площадь: 33, 42, 33 и 65 кв. м.
* Жилая площадь: 24, 32, 20 и 48 кв. м.
* Арендная плата: 39, 50, 38 и 77 тысяч рублей соответственно.

В том же доме появилась новая квартира общей площадью 50 кв. м, из которых жилая — 40 кв. м.

На основе имеющихся данных выберите оптимальную арендную плату для новой квартиры.

Запишем данные в векторном виде.

* Вектор общих площадей: ${\overrightarrow{s}}_{\textrm{о}\textrm{б}\textrm{щ}}=\left( \begin{array}{c} 33 \\ \mathrm{42} \\ 33 \\ 65 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Вектор жилых площадей: ${\overrightarrow{s}}_{\textrm{ж}\textrm{и}\textrm{л}}=\left( \begin{array}{c} 24 \\ \mathrm{32} \\ 20 \\ 48 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Стоимость аренды: $\overrightarrow{p}=\left( \begin{array}{c} 39 \\ \mathrm{50} \\ 38 \\ 77 \end{array} \right)\ [\textrm{т}\textrm{ы}\textrm{с}.\ \textrm{р}\textrm{у}\textrm{б}]$

Нам нужно порекомендовать оптимальную арендную плату для новой квартиры, исходя из опыта аренды предыдущих четырёх квартир.

Ключом к решению является линейная зависимость векторов: можно заметить, что вектор $\overrightarrow{p}$ является линейной комбинацией векторов ${\overrightarrow{s}}_{\textrm{о}\textrm{б}\textrm{щ}}$ и ${\overrightarrow{s}}_{\textrm{ж}\textrm{и}\textrm{л}}$ с коэффициентами $w_1=1$ и $w_2=1/4$:

$\overrightarrow{p}={\omega }_1{\overrightarrow{s}}_{\textrm{о}\textrm{б}\textrm{щ}}+{\omega }_2{\overrightarrow{s}}_{\textrm{ж}\textrm{и}\textrm{л}}=\left( \begin{array}{c} 33 \\ \mathrm{42} \\ 33 \\ 65 \end{array} \right)+\frac{1}{4}\left( \begin{array}{c} 24 \\ \mathrm{32} \\ 20 \\ 48 \end{array} \right)=\left( \begin{array}{c} 33 \\ \mathrm{42} \\ 33 \\ 65 \end{array} \right)+\left( \begin{array}{c} 6 \\ \mathrm{8} \\ 5 \\ 14 \end{array} \right)=\left( \begin{array}{c} 39 \\ \mathrm{50} \\ 38 \\ 77 \end{array} \right)[\textrm{т}\textrm{ы}\textrm{с}.\ \textrm{р}\textrm{у}\textrm{б}]$

Составим вектор из коэффициентов $w$ линейной комбинации $\overrightarrow{\omega }=\left( \begin{array}{c} {\omega }_1 \\ {\omega }_2 \end{array} \right)=\left( \begin{array}{c} 1 \\ \frac{1}{4} \end{array} \right)$ и скалярно умножим его на вектор новой квартиры $\overrightarrow{x}=\left( \begin{array}{c} 50 \\ 40 \end{array} \right)$:

$p=\left(\overrightarrow{\omega },\overrightarrow{x}\right)=\ 50+\frac{1}{4}40=60\ [\textrm{т}\textrm{ы}\textrm{с}.\ \textrm{р}\textrm{у}\textrm{б}]$

Ух тыж как пиздато, но в реальности всё немного интереснее

Запишем **более реальные** данные в векторном виде.

* Вектор общих площадей: ${\overrightarrow{s}}_{\textrm{о}\textrm{б}\textrm{щ}}=\left( \begin{array}{c} 33 \\ \mathrm{42} \\ 33 \\ 65 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Вектор жилых площадей: ${\overrightarrow{s}}_{\textrm{ж}\textrm{и}\textrm{л}}=\left( \begin{array}{c} 24 \\ \mathrm{32} \\ 20 \\ 48 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Стоимость аренды: $\overrightarrow{p}=\left( \begin{array}{c} 40 \\ \mathrm{48,46} \\ 38 \\ 77 \end{array} \right)\ [\textrm{т}\textrm{ы}\textrm{с}.\ \textrm{р}\textrm{у}\textrm{б}]$

Теперь вектор арендной платы **не выражается линейно** через векторы площадей.

Изобразим данные геометрически. Так как векторы четырёхмерные, мы не сможем получить корректное геометрическое решение. Однако можно получить условное графическое представление, которого нам будет достаточно для решения задачи.

Векторы общей и жилой площади лежат в некоторой плоскости, обозначенной синим цветом. Вектор $\overrightarrow{p}$ из первого условия задачи линейно выражается через них, а значит, лежит в той же плоскости. 

Вектор $\overrightarrow{p}_{реал}$ выразить через векторы площадей уже нельзя, а значит он не лежит в синей плоскости.

<img src=m1_img8.png width=600>

Красный вектор $\overrightarrow{n}$ как разница между $\overrightarrow{p}_{реал}$ и $\overrightarrow{p}$ символизирует влияние других, внешних, факторов на стоимость аренды. Вычислим его координаты и найдём скалярное произведение с вектором $\overrightarrow{p}$:

<img src=m1_img9.png>

Скалярное произведение равно нулю. Это значит, что угол между векторами $\overrightarrow{p}$ и $\overrightarrow{n}$ равен 90 градусов, то есть $\overrightarrow{p}\bot \overrightarrow{n}$. Говорят: вектор является ортогональной проекцией вектора $\overrightarrow{p}_{реал}$ на плоскость.

>И как теперь с этим жить??
>
>Это значит, что среди всех возможных линейных комбинаций векторов общей и жилой площади наше изначальное — $\overrightarrow{p}_{реал}$ наилучший прогноз арендной платы. 
>
>Потому что ортогональная проекция по определению является вектором **с ближайшим расстоянием** к вектору, который проецируется.
>
>Другими словами, если другой информации нет, то 60 тысяч рублей, которые мы получили в первом условии задачи, — и есть наш лучший прогноз стоимости аренды новой квартиры.


На самом деле, решая данную задачу, мы с вами только что построили простейшую модель линейной регрессии в векторном виде. Давайте посмотрим на задачу под другим углом.

У нас было:

* два вектора $\overrightarrow{s}_{общ}$ и $\overrightarrow{s}_{жил}$ — признаки (факторы), которые описывают объекты в данных;

* вектор $\overrightarrow{p}_{реал}$ — целевой признак, который мы пытаемся предсказать.

Мы построили такую линейную комбинацию $\overrightarrow{p}$ из векторов $\overrightarrow{s}_{общ}$ и $\overrightarrow{s}_{жил}$, при которой ошибка между вектором и линейной комбинацией $\overrightarrow{e}=\overrightarrow{p}_{реал}-\overrightarrow{p}$ была бы минимальной.

Коэффициенты линейной комбинации $w_1$ и $w_2$ —это наши любимые коэффициенты линейной регрессии (правда, в классической линейной регрессии есть ещё коэффициент добавочного смещения $w_0$, но эту задачу мы решили без его участия).

>У вас, должно быть, возник вопрос: как ищутся коэффициенты линейной комбинации $w_1$ и $w_2$ ? Не искать же их полным перебором.

На этот вопрос в своё время ответил Гаусс и создал знакомый нам метод наименьших квадратов (`МНК`), который мы уже многократно использовали в модулях по машинному обучению. Но, чтобы познакомиться с `МНК` поближе с математической точки зрения, нам с вами необходимо изучить тему матриц и матричных преобразований.

## Неинформативные признаки геометрическое отображение

Пусть появилась дополнительная информация — нежилая площадь.

Позволит ли она улучшить прогноз по аренде новой квартиры? (спойлер - нет)

* Вектор общих площадей: ${\overrightarrow{s}}_{\textrm{о}\textrm{б}\textrm{щ}}=\left( \begin{array}{c} 33 \\ \mathrm{42} \\ 33 \\ 65 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Вектор жилых площадей: ${\overrightarrow{s}}_{\textrm{ж}\textrm{и}\textrm{л}}=\left( \begin{array}{c} 24 \\ \mathrm{32} \\ 20 \\ 48 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Вектор нежилых площадей: ${\overrightarrow{s}}_{\textrm{н}\textrm{е}\textrm{ж}\textrm{и}\textrm{л}}=\left( \begin{array}{c} 9 \\ \mathrm{10} \\ 13 \\ 17 \end{array} \right)\ [\textrm{к}\textrm{в}.\ \textrm{м}]$

* Стоимость аренды: $\overrightarrow{p}=\left( \begin{array}{c} 40 \\ \mathrm{48,46} \\ 38 \\ 77 \end{array} \right)\ [\textrm{т}\textrm{ы}\textrm{с}.\ \textrm{р}\textrm{у}\textrm{б}]$

Нежилая площадь является разностью общей и жилой, а значит, лежит в той же плоскости. То есть вектор $\overrightarrow{s}_{нежил}$ линейно выражается через векторы $\overrightarrow{s}_{общ}$ и $\overrightarrow{s}_{жил}$

А это значит, что проекция $\overrightarrow{p}_{реал}$ на эту плоскость не поменяется, то есть и наилучший прогноз останется без изменений.

<img src=m1_img10.png width=600>

В `Hut_Paradise_DF` представлен фрагмент базы данных агентства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [21]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [29]:
# Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values
Hut_Paradise_values = Hut_Paradise_DF.values
# Найдите вектор параметров квартиры номер 5
print('параметры квартиры номер 5:\n',Hut_Paradise_values[4])
# Найдите вектор этажей всех квартир
print('вектор этажей всех квартир:\n',Hut_Paradise_values[:,3])
# Вычислите вектор нежилой площади
print('вектор нежилой площади всех квартир:\n',Hut_Paradise_values[:,1]-Hut_Paradise_values[:,5])

параметры квартиры номер 5:
 [40 33  1  6 20 16]
вектор этажей всех квартир:
 [ 5 12 10  3  6 13  8 21  5]
вектор нежилой площади всех квартир:
 [13 12 15 13 17  9 20 15 25]


In [45]:
# Пусть в первой квартире один просмотр занимает 10 минут, 
# во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, 
# в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.
# Найдите продолжительность просмотров в минутах во всех квартирах за две недели.
time = np.array([10,20,30,15,5,40,20,8,20])
sum(time)*14

2352

In [49]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

#Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3. Выберите координаты полученного вектора
d = 2*v-3*w
print('linear combination:',d)

#Будет ли эта комбинация ортогональна вектору ?
if np.dot(d,u) == 0:
    print('веткор d ортогонален вектору u')
else:
    print('веткор d неортогонален вектору u')

linear combination: [-3 14  3  4  2]
веткор d ортогонален вектору u


# 4. Основные понятия линал. Матрицы и действия над ними <a class="anchor" id=4></a>

[к содержанию](#0)

# 5. Матрицы. Практика <a class="anchor" id=5></a>

[к содержанию](#0)

# 6. Матричное умножение <a class="anchor" id=6></a>

[к содержанию](#0)

# 7. Матричное умножение. Практика <a class="anchor" id=7></a>

[к содержанию](#0)

# 8. Обратная матрица. Определитель матрицы <a class="anchor" id=8></a>

[к содержанию](#0)

# 9. СЛАУ. Линейная зависимость векторов. Ранг матрицы. Базис <a class="anchor" id=9></a>

[к содержанию](#0)

# 10. Обратная матрица, определитель, ранг. Практика <a class="anchor" id=10></a>

[к содержанию](#0)

# 11. Итоги <a class="anchor" id=11></a>

[к содержанию](#0)