In [2]:
import numpy as np

# Table of content

1. [creating-arrays-commands](#1-creating-arrays-commands)
2. [initial-placeholders](#2-initial-placeholders)
3. [inspecting-properties](#3-inspecting-properties)
4. [saving-and-loading-file](#4-saving-and-loading-file)
5. [sorting-searching-and-counting](#5-sorting-searching-and-counting)
6. [array-manipulation](#6-array-manipulation)
7. [combining-and-splitting-commands](#7-combining-and-splitting-commands)
8. [indexing-slicing-and-subsetting](#8-indexing-slicing-and-subsetting)
10. [numpy-array-mathematics](#10-numpy-array-mathematics)

| Тип данных | Описание |
| :---: | :--- |
| `bool` | Булевы значения (`True` или `False`) хранятся в виде байтов |
| `int` | Тип по умолчанию — целое число (обычно `int64` или `int32`) |
| `intc` | Идентичный `int` в `C` (обычно `int32` или `int64`) |
| `intp` | Целое число для использования в качестве индексов (то же, что и `size_t` в `C`, обычно `int32` или `int64`) |
| `int8` | Байт (от `-128` до `127`) |
| `int16` | Целое число (от `-32 768` до `32 767`) |
| `int32` | Целое число (от `-2 147 483 648` до `2 147 483 647`) |
| `int64` | Целое число (от `-9 223 372 036 854 775 808` до `9 223 372 036 854 775 807`) |
| `uint8` | Целое число без знака (от `0` до `255`) |
| `uint16` | Целое число без знака (от `0` до `65 535`) |
| `uint32` | Целое число без знака (от `0` до `4 294 967 295`) |
| `uint64` | Целое число без знака (от `0` до `18 446 744 073 709 551 615`) |
| `float` | Обозначение `float64` |
| `float16` | Число с плавающей точкой половинной точности; бит на знак, 5-битная экспонента, 10-битная мантисса |
| `float32` | Число с плавающей точкой единичной точности; бит на знак, 8-битная экспонента, 23-битная мантисса |
| `float64` | Число с плавающей точкой двойной точности; бит на знак, 11-битная экспонента, 52-битная мантисса |
| `complex` | Обозначение `complex128` |
| `complex64` | Комплексное число, представленное двумя 32-битными `float` (с действительной и мнимой частями) |
| `complex128` | Комплексное число, представленное двумя 64-битными `float` (с действительной и мнимой частями) |



# 1. Creating Arrays Commands

[up ⬆️](#table-of-content)

In [3]:
# create a NumPy array from a list 
li = [1, 2, 3, 4]  
print(np.array(li)) 
  
# create a NumPy array from a tuple 
tup = (5, 6, 7, 8) 
print(np.array(tup)) 
  
# create a NumPy array using fromiter() 
iterable = (a for a in range(8)) 
print(np.fromiter(iterable, float))

[1 2 3 4]
[5 6 7 8]
[0. 1. 2. 3. 4. 5. 6. 7.]


In [4]:
# create a NumPy array from a list 
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
print(np.array([list_1, list_2, list_3])) 
  
# create a NumPy array using numpy.empty() 
print(np.empty([4, 3], dtype=int))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 2. Initial Placeholders

[up ⬆️](#table-of-content)

| Initial Placeholders for 1D Array | Syntax | Example |
| :---: | :---: | :---: |
| [arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) | numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None) | np.arange(1, 10) |
| [linespace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) | numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) | np.linspace(1, 10, 3) |
| [zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) | numpy.zeros(shape, dtype=float, order='C', *, like=None) | np.zeros(5, dtype=int) |
| [zeros_like()](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html) | numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None) | np.zeros_like(array) |
| [ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) | numpy.ones(shape, dtype=None, order='C', *, like=None) | np.ones(5, dtype=int) |
| [ones_like()](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html) | numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None) | np.ones_like(array) |
| [random.rand()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html#numpy-random-rand) | random.rand(d0, d1, ..., dn) | np.random.rand(5) |
| [random.randint()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy-random-randint) | random.randint(low, high=None, size=None, dtype=int) | np.random.randint(5, size=10) |

In [7]:
# create a NumPy array using numpy.arange() 
print(np.arange(1, 10)) 
  
# create a NumPy array using numpy.linspace() 
print(np.linspace(1, 10, 3)) 
  
# create a NumPy array using numpy.zeros() 
print(np.zeros(5, dtype=int)) 
  
# create a NumPy array using numpy.ones() 
print(np.ones(5, dtype=int)) 
  
# create a NumPy array using numpy.random.rand() 
print(np.random.rand(5)) 
  
# create a NumPy array using numpy.random.randint() 
print(np.random.randint(5, size=10)) 

[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]
[0 0 0 0 0]
[1 1 1 1 1]
[0.20253872 0.0493128  0.16115816 0.50970267 0.24081023]
[3 4 1 2 3 3 2 1 4 2]


| Initial Placeholders for 2D Array | Syntax | Example |
| :---: | :---: | :---: |
| [zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) | numpy.zeros(shape, dtype=float, order='C', *, like=None) | np.zeros([4, 3], dtype = np.int32) |
| [zeros_like()](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html) | numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None) | np.zeros_like(array) |
| [ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) | numpy.ones(shape, dtype=None, order='C', *, like=None) | np.ones([4, 3], dtype = np.int32) |
| [ones_like()](https://numpy.org/doc/stable/reference/generated/numpy.ones_like.html) | numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None) | np.ones_like(array) |
| [full()](https://numpy.org/doc/stable/reference/generated/numpy.full.html#numpy.full) | numpy.full(shape, fill_value, dtype=None, order='C', *, like=None) | np.full([2, 2], 67, dtype = int) |
| [eye()](https://numpy.org/doc/stable/reference/generated/numpy.eye.html#numpy.eye) | numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None) | np.eye(4) |

In [8]:
# create a NumPy array using numpy.zeros() 
print(np.zeros([4, 3], dtype = np.int32)) 
  
# create a NumPy array using numpy.ones() 
print(np.ones([4, 3], dtype = np.int32)) 
  
# create a NumPy array using numpy.full() 
print(np.full([2, 2], 67, dtype = int)) 
  
# create a NumPy array using numpy.eye() 
print(np.eye(4))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[67 67]
 [67 67]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 3. Inspecting Properties

[up ⬆️](#table-of-content)

| Inspecting Properties | Example |
| :---: | :--- |
| [size](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html) | ndarray.size |
| [shape](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) | ndarray.shape |
| [dtype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.dtype.html) | ndarray.dtype |

In [11]:
# Two dimensional numpy array 
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
arr = np.array([list_1, list_2, list_3])  
  
# check size of the array 
print("Size:", arr.size) 
  
# check length of the array 
print("Length:", len(arr)) 
  
# check shape of the array 
print("Shape:", arr.shape) 
  
# check dtype of the array elements 
print("Datatype:", arr.dtype) 
  
# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype) 
  
# convert array to list 
lis = arr.tolist() 
print("\nList:", lis) 
print(type(lis))

Size: 12
Length: 3
Shape: (3, 4)
Datatype: int32
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
float64

List: [[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0]]
<class 'list'>


# 4. Saving and Loading File

[up ⬆️](#table-of-content)

| Importing & Exporting | Syntax | Example |
| :---: | :--- | :--- |
| [save()](https://numpy.org/doc/stable/reference/generated/numpy.save.html#numpy.save) | numpy.save(file, arr, allow_pickle=True, fix_imports=True) | np.save(outfile, x) |
| [savetxt()](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html) | numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None) | np.savetxt('test.out', x, delimiter=',') |
| [load()](https://numpy.org/doc/stable/reference/generated/numpy.load.html) | numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII', *, max_header_size=10000) | np.load('*.npy') |
| [loadtxt()](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) | numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None) | np.loadtxt('*.txt') |
| [genfromtxt()](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html#numpy-genfromtxt) | numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+, -./:;<=>?@[\\]^{}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None) | np.genfromtxt(f, delimiter=',') |

In [14]:
# the array is saved in the file geekfile.npy 
np.save("array", np.arange(5)) 
  
# the array is loaded into b 
print(np.load("array.npy"))

x = np.arange(0, 10, 1) 
print(x) 
  
# X array saved in geekfile.txt 
c = np.savetxt("array.txt", x, delimiter =', ')

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [16]:
# save txt as csv file
a = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
np.savetxt("my_csv.csv", a, delimiter=",")

# read from csv file
df = np.genfromtxt('my_csv.csv', delimiter=',')
df

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# 5. Sorting, searching and counting

[up ⬆️](#table-of-content)

| SSC | Syntax | Example |
| :---: | :--- | :--- |
| [sort](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html) | ndarray.sort(axis=-1, kind=None, order=None) | array.sort() |
| [sort()](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort) | numpy.sort(a, axis=-1, kind=None, order=None) | np.sort(array) |  
| [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html#numpy.argsort) | numpy.argsort(a, axis=-1, kind=None, order=None) | np.argsort(array) |
| [where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html) | numpy.where(condition, [x, y, ]/) | np.where(x < y, x, 10 + y) |


In [112]:
# sorting a one dimensional 
# numpy array using numpy.sort() 
a = np.array([12, 15, 10, 1]) 
print("Array before sorting",a) 
a.sort() 
print("Array after sorting",a)

Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]


In [111]:
# sorting a two dimensional 
# numpy array using numpy.sort() 
# sort along the first axis 
a = np.array([[12, 15], [10, 1]]) 
arr1 = np.sort(a, axis = 0)     
print ("Along first axis : \n", arr1)

# sort along the last axis 
a = np.array([[10, 15], [12, 1]]) 
arr2 = np.sort(a, axis = -1)     
print ("\nAlong Last axis : \n", arr2) 
  
a = np.array([[12, 15], [10, 1]]) 
arr1 = np.sort(a, axis = None)     
print ("\nAlong none axis : \n", arr1)     

Along first axis : 
 [[10  1]
 [12 15]]


In [110]:
# where()
a = np.array([[0, 1, 2],
              [0, 2, 4],
              [0, 3, 6]])
np.where(a < 4, a, -1)

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

# 6. Array Manipulation

[up ⬆️](#table-of-content)

| Array Manipulation | Syntax | Example |
| :---: | :--- | :--- |
| [append()](https://numpy.org/doc/stable/reference/generated/numpy.append.html#numpy.append) | numpy.append(arr, values, axis=None) | np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]]) |
| [insert()](https://numpy.org/doc/stable/reference/generated/numpy.insert.html) | numpy.insert(arr, obj, values, axis=None) | np.insert([1, 4, 5], 1, [2, 3]) |
| [reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) | numpy.reshape(a, newshape, order='C') | np.arange(6).reshape((3, 2)) | 
| [resize()](https://numpy.org/doc/stable/reference/generated/numpy.resize.html) | numpy.resize(a, new_shape) | np.resize(np.array([[0,1],[2,3],[4,5]]), (1, 9)) | 
| [swapaxes](https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html) | numpy.swapaxes(a, axis1, axis2) | np.swapaxes(np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]]), 0, 1) |


In [104]:
# append()
print(f'{np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])}\n')

[1 2 3 4 5 6 7 8 9]



In [105]:
# insert()
print(f'{np.insert([1, 4, 5], 1, [2, 3])}\n')

[1 2 3 4 5]



In [106]:
# reshape()
print(f'a is {np.arange(6)}\n')
print(f'a reshaped is \n{np.arange(6).reshape((3, 2))}\n')

a is [0 1 2 3 4 5]

a reshaped is 
[[0 1]
 [2 3]
 [4 5]]



In [108]:
# resize()
print(f'a is \n{np.array([[0,1],[2,3],[4,5]])}\n')
print(f'a resized is \n{np.resize(np.array([[0,1],[2,3],[4,5]]), (1, 9))}\n')

a is 
[[0 1]
 [2 3]
 [4 5]]

a resized is 
[[0 1 2 3 4 5 0 1 2]]



In [109]:
# swapaxes()
a = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
print(f'a is \n{a}\n')
b = np.swapaxes(a, 0, 1)
print(f'a swapaxes is \n{b}\n')

a is 
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]

a swapaxes is 
[[  1  11 111]
 [  2  22 222]
 [  3  33 333]]



| Array Manipulation | Syntax | Example |
| :---: | :--- | :--- |
| [flatten()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) | ndarray.flatten(order='C') | np.array([[1,2], [3,4]]).flatten() |
| [.T](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.T.html) | ndarray.T | ndarray.T |
| [rot90()](https://numpy.org/doc/stable/reference/generated/numpy.rot90.html) | numpy.rot90(m, k=1, axes=(0, 1)) | np.rot90(np.array([[1, 2, 3], [11, 22, 33]]), -1) |

In [101]:
# flatten()
a = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
print(f'a is \n{a}\n')
print(f'a.flatten is \n{a.flatten()}\n')

a is 
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]

a.flatten is 
[  1   2   3  11  22  33 111 222 333]



In [102]:
# .T
a = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
print(f'a is \n{a}\n')
print(f'a.T is \n{a.T}\n')

a is 
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]

a.T is 
[[  1  11 111]
 [  2  22 222]
 [  3  33 333]]



In [103]:
# rot90()
print(f'a rot90 is \n{np.rot90(a, -1)}\n')

a rot90 is 
[[111  11   1]
 [222  22   2]
 [333  33   3]]



# 7. Combining and Splitting Commands

[up ⬆️](#table-of-content)

| Array Manipulation | Syntax | Example |
| :---: | :--- | :--- |
| [concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy-concatenate) | numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind") | np.concatenate((a, b), axis=0) |
| [stack()](https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack) | numpy.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind') | np.stack((a, b)) |
| [hstack()](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html) | numpy.hstack(tup, *, dtype=None, casting='same_kind') | np.hstack((a,b)) |
| [vstack()](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) | numpy.vstack(tup, *, dtype=None, casting='same_kind') | np.vstack((a,b)) |
| [split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html) | numpy.split(ary, indices_or_sections, axis=0) | np.split(x, 3) |
| [hsplit()](https://numpy.org/doc/stable/reference/generated/numpy.hsplit.html) | numpy.hsplit(ary, indices_or_sections) | np.hsplit(a, 3) | 
| [vsplit()](https://numpy.org/doc/stable/reference/generated/numpy.vsplit.html) | numpy.vsplit(ary, indices_or_sections) | np.vsplit(a, 3) | 


In [99]:
# concatenate()
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
# stack()
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
# hstack()
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [117]:
# vstack
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [128]:
a = np.arange(10)
np.split(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [129]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.hsplit(a, 3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [130]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.vsplit(a, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

# 8. Indexing, Slicing and Subsetting

[up ⬆️](#table-of-content)

[How to index ndarrays](https://numpy.org/doc/stable/user/how-to-index.html)

| ISS | Example |
| - | - |
| Subsetting | arr[np.array([1, 3, -3])] |
| Sclicing | arr[-2:7:1] |
| Integer Indexing | a[[0 ,1 ,2 ],[0 ,0 ,1]] |
| Boolean Indexing | a[a>50] |

In [139]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'a is \n{a}\n')
print(f'a[0,1] is {a[1,1]}\n')

a is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

a[0,1] is 5



In [147]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'a is \n{a}\n')
print(f'3 col \n{a[:,2]}\n')
print(f'3 row \n{a[2:]}\n')

a is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3 col 
[3 6 9]

3 row 
[[7 8 9]]



In [155]:
a = np.arange(100).reshape(10, 10)
print(f'a is \n{a}\n')
print(f'a[2:5, 5:2] \n{a[2:7, 2:7]}\n')

a is 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

a[2:5, 5:2] 
[[22 23 24 25 26]
 [32 33 34 35 36]
 [42 43 44 45 46]
 [52 53 54 55 56]
 [62 63 64 65 66]]



In [162]:
a = np.arange(100).reshape(10, 10)
print(f'a is \n{a}\n')
print(f'a >= 80 \n{a >= 80}\n')
print(f'a[a >= 80] \n{a[a >= 80]}\n')

a is 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

a >= 80 
[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]

a[a >= 80] 
[80 81 82

In [175]:
a = np.arange(-10, 10).reshape(2, 2, 5)
print(f'a is \n{a}\n')
a[a < 0] = 0
print(f'a after changing is \n{a}\n')

a is 
[[[-10  -9  -8  -7  -6]
  [ -5  -4  -3  -2  -1]]

 [[  0   1   2   3   4]
  [  5   6   7   8   9]]]

a after changing is 
[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]



# 10. NumPy Array Mathematics

[up ⬆️](#table-of-content)